In [1]:
import torch
from torch import nn # nn contains all of PyTorch's building blocks for neural networks
import matplotlib.pyplot as plt

# Check PyTorch version
torch.__version__

'1.13.0+cu117'

In [ ]:
# Create a Linear Regression model class
class LinearRegressionModel(nn.Module): # <- almost everything in PyTorch is a nn.Module (think of this as neural network lego blocks)
    def __init__(self):
        super().__init__() 
        self.weights = nn.Parameter(torch.randn(1, # <- start with random weights (this will get adjusted as the model learns)
                                                dtype=torch.float), # <- PyTorch loves float32 by default
                                   requires_grad=True) # <- can we update this value with gradient descent?)

        self.bias = nn.Parameter(torch.randn(1, # <- start with random bias (this will get adjusted as the model learns)
                                            dtype=torch.float), # <- PyTorch loves float32 by default
                                requires_grad=True) # <- can we update this value with gradient descent?))

    # Forward defines the computation in the model
    def forward(self, x: torch.Tensor) -> torch.Tensor: # <- "x" is the input data (e.g. training/testing features)
        return self.weights * x + self.bias # <- this is the linear regression formula (y = m*x + b)

Create a Car class with two instance attributes:

    .color, which stores the name of the car’s color as a string
    .mileage, which stores the number of miles on the car as an integer

Then instantiate two Car objects—a blue car with 20,000 miles and a red car with 30,000 miles—and print out their colors and mileage. Your output should look like this

The blue car has 20,000 miles.
The red car has 30,000 miles.


In [9]:
class Car():
    def __init__(self, color, mileage):
        self.color = color
        self.mileage = mileage
    def __str__(self):
        return f" The {self.color} car has {self.mileage} miles"

In [12]:
print(Car('blue',20000)), print(Car('red',30000))

 The blue car has 20000 miles
 The red car has 30000 miles


(None, None)

In [14]:
class Dog:
    species = "Canis familiaris"

    def __init__(self, name, age):
        self.name = name
        self.age = age

    def __str__(self):
        return f"{self.name} is {self.age} years old"

    def speak(self, sound):
        return f"{self.name} says {sound}"


In [15]:
class GoldenRetriever(Dog):
    def speak(self, sound='Bark'):
        return super().speak(sound)

In [16]:
GoldenRetriever.speak()

TypeError: speak() missing 1 required positional argument: 'self'

In [1]:
from tqdm import tqdm


In [3]:
e_l = []
for i in tqdm(range(10)):
    e_l.append(i)


100%|████████████████████████████████████████| 10/10 [00:00<00:00, 92385.55it/s]


In [6]:
for i in enumerate(e_l):
    print (i)

(0, 0)
(1, 1)
(2, 2)
(3, 3)
(4, 4)
(5, 5)
(6, 6)
(7, 7)
(8, 8)
(9, 9)


In [2]:
z = torch.rand(3,4)

In [3]:
z

tensor([[0.8803, 0.0507, 0.9714, 0.5261],
        [0.6358, 0.8941, 0.8564, 0.3092],
        [0.1860, 0.1655, 0.2180, 0.3081]])

In [4]:
z +1

tensor([[1.8803, 1.0507, 1.9714, 1.5261],
        [1.6358, 1.8941, 1.8564, 1.3092],
        [1.1860, 1.1655, 1.2180, 1.3081]])

In [6]:
nn.init.xavier_normal_(torch.empty(3, 5))


tensor([[-0.8010, -0.4727,  0.8487, -0.2694,  0.5072],
        [-0.3609, -0.1334, -0.1569, -0.5035, -0.5104],
        [-0.0616, -0.3457, -0.1665, -0.0972, -0.2832]])

In [7]:
random.uniform(0, 1)

NameError: name 'random' is not defined

In [10]:
torch.rand(1)

tensor([0.7558])